object_list:
  - name: biscuits
    group: green
    offset: 0.0
  - name: soap
    group: green
    offset: 0.0
  - name: book
    group: red
    offset: 0.0
  - name: soap2
    group: red
    offset: 0.0
  - name: glue
    group: red
    offset: 0.0
